### PR TITLE
Tokenizer model (eos1mxi)

### PR DESCRIPTION
**Pull request by russelljeffrey**
Making a pull request for eos1mxi

### CODE REVIEW

**Comment by carcablop** [comment]
Hi @russelljeffrey. 
At first glance, reviewing the metadata.json file, I find some metadata that is not correct, and I suggest correcting the following:
1. Input is a compound, not a "text". The model input is SMILES.
2. I see that the result of the model is a version of the tokenized smile, where the tokens are separated by spaces. The result is a tokenized smile text string separated by spaces.
In the interpretation of the model, the interpretation of the model results must also be added. How to interpret the model results and perhaps also the SPE training process.

I don't see workflows for the other changes.
I don't see that you have made changes to the docker file. I ask this because I imagine that some packages had to be installed within a development environment to test the model.

Could you provide an example of model output? You can share this in the Model Request thread.
Has the model been run within ersilia with the --repo_path option on your system?
Check before making another pull request that the previous options work. You can see the guide to incorporate the model here: [https://ersilia.gitbook.io/ersilia-book/ersilia-model-hub/contribute-models/model-incorporation-workflow](https://ersilia.gitbook.io/ersilia-book/ersilia-model-hub/contribute-models/model-incorporation-workflow)
You can see point 5, the option to run it with the --repo_path option.

I hope this can help.

**Comment by GemmaTuron** [comment]
Hi @russelljeffrey!

The model test is failing with: 
ModuleNotFoundError: No module named 'fastprogress'
You need to update the Dockerfile to add this package and any other that is required. Unless very strong reasons, it would be best that you use newer py versions (i.e 310 for example) - use the first line of the Dockerfile to modify that
Also, always pin the versions of the packages, I see you have rdkit as requirement but no specific version. Also probably other packages are needed?

In main.py I also observe the following:
```
# parse arguments
input_file = sys.argv[1]
#output_file = sys.argv[2]

spe_vob = codecs.open("../data/SPE_ChEMBL.txt")
spe = SPE_Tokenizer(spe_vob)

# current file directory
root = os.path.dirname(os.path.abspath(__file__))
```

The output file is commented out, it should not be
You are not using the absolute paths (root) to load the spevob, please use the abspath as inside Ersilia many directories are created and this might give issues

**Comment by GemmaTuron** [comment]
Hi @russelljeffrey 

The tests are failing due to some missing packages. Those must be stated in the dockerfile of the model. Please make sure you follow the instructions to test the model before opening a PR, this way it will be much faster to debug. Use the repo_path flag to fetch the model locally and check it works within Ersilia before opening a PR.

**Comment by russelljeffrey** [comment]
Hi @GemmaTuron. I will make the necessary modifications and very soon make a PR so that Model Test can run successfully

**Comment by GemmaTuron** [comment]
Hi @russelljeffrey !

I just wanted to check in progress of this model, I totally understand if you are too busy. Please let me know if you don't think it is feasible to finish in the next weeks and I'll assign this model to someone else. Thanks so much for your effort!

**Comment by russelljeffrey** [comment]
Hi @GemmaTuron . The model will be completed before the end of this week. My main problem was with docker and its model dependency.

**Comment by GemmaTuron** [comment]
Hi everyone!

We need to finish up this model issue. @russelljeffrey thanks for your contributions, I understand you are currently busy to tackle this, if so, do not worry we will assign it to someone else in the community so we can close this open model request.

**Comment by GemmaTuron** [comment]
I'll close this PR as the model has been incorporated

**Pull request closed without merging**
