### PR TITLE
Corrections Applied

### PR DESCRIPTION
**Pull request by Richiio**
Hi @GemmaTuron, the corrections you asked me to make have been made.

### CODE REVIEW

**Comment by GemmaTuron** [comment]
Hi @Richiio !

The headers won't be added as we want, since only one single "outcome" will be generated. We could add dynamic headers that say for example: token1, token2...
I am referring to this line:
```
    writer.writerow(["outcome"])  # header
    for o in outputs:
        writer.writerow([o])
        writer.writerow(o)
```
You can have a look at other models to see how this is done!
Also, when making the changes can you paste here the output you get to make sure it's the best format?

Thanks!

**Comment by Richiio** [comment]
@GemmaTuron It's been corrected

**Comment by GemmaTuron** [comment]
Hi @Richiio 

Great, but could you please paste an example of the output you are getting now as I asked, just to be sure we have the right format! thanks :)

**Comment by Richiio** [comment]
Here is the output @GemmaTuron 
[output.csv](https://github.com/ersilia-os/eos1mxi/files/13820087/output.csv)

**Pull request merged**
